void main
(
	float2 iTexCoord0 : TEXCOORD0,
	
	out float4 oColor : COLOR,

	uniform sampler2D diffuseMap0 : register(s0)
)
{
	// Get the texture color

	float4 color = tex2D( diffuseMap0, iTexCoord0 );

	// Reject it if the color is not bright enough

	if ( (color.r < 0.90) && (color.g < 0.90) && (color.b < 0.90) )
		color = float4(0,0,0,0);

	// Return color!

	oColor = color;
}
