this.TipDef <- [];
local tip = {};
tip.Text <- "";
tip.Text += "<font name=\"Maiandra\" size=\"32\" color=\"724d00\">Moving in Earth Eternal</font><br><br>";
tip.Text += "<font name=\"Maiandra\" size=\"16\" color=\"2b1b00\">A few helpful keys to get you started on your adventures in Earth Eternal!<br><br></font>";
tip.Text += "<font name=\"Maiandra\" size=\"16\" color=\"2b1b00\"><b>Movement Keys:</b><br/>";
tip.Text += "<br/>";
tip.Text += "A W D S - Control Movement<br>";
tip.Text += "Space - Jump<br>";
tip.Text += "Z - Auto Run<br>";
this.TipDef.append(tip);
local tip = {};
tip.Text <- "";
tip.Text += "<font name=\"Maiandra\" size=\"32\" color=\"724d00\">Basic Combat</font><br><br>";
tip.Text += "<font name=\"Maiandra\" size=\"16\" color=\"2b1b00\">There are two basic forms of auto attack in Earth Eternal: Ranged and Melee.  You need a range weapon equiped to take advantage of the auto ranged attack.<br/><br/></font>";
tip.Text += "<font name=\"Maiandra\" size=\"16\" color=\"2b1b00\"><b>Combat Keys:</b><br/>";
tip.Text += "<br/>";
tip.Text += "1 - Auto Melee Attack Target<br/>";
tip.Text += "2 - Auto Range Attack Target<br/>";
this.TipDef.append(tip);
